### PR TITLE
Ban system

### LINKED ISSUE #616: Ban Table/Prison
Introduce a ban table that holds a key, type, expiry scheme that effectively bans a vtxo or a vtxo script. When a vtxo is banned, it cannot be used for ark txs or intent registration. 

admin rpc should have crud for bans. Failing a round is a ban. 

Store a log of ban history.

Define a default ban interval (6-10 * round intervals)

### LINKED ISSUE #713: Add admin APIs to ban vtxos
Related to #616

### PR DESCRIPTION
**Pull request by louisinger**
This PR adds a new banning mechanism during settlement session. If an owner of a VTXO made the batch session to fail, all vtxos locked by the output script will be "locked" for `10 * roundInterval`.

The `Conviction` domain and the associated `ConvictionRepository` interface allows storing all the ban occurring during batch sessions. Each conviction is associated with a `CrimeType` which can be one of :
* Musig2NonceSubmission : the user registered a batch tree cosigner pubkey but didn't submit nonces.
* Musig2SignatureSubmission : the user registered a batch tree cosigner pubkey but didn't submit signatures.
* Musig2InvalidSignature : the user registered an invalid batch tree signature.
* ForfeitSubmission : the user registered a VTXO requiring forfeit transaction but didn't submit it.
* ForfeitInvalidSignature : the user provided a forfeit transaction with invalid signature.
* BoardingInputSubmission : the user registered boarding input but didn't provide a valid commitment tx signature. 

Once a VTXO script is banned, any `RegisterIntent` call, spending an input (boarding or VTXO) locked by the script, will be rejected.

it closes #616 
it closes #713

@Kukks @sekulicd @altafan please review

## Summary by CodeRabbit

- **New Features**
  - Admin API to list/get convictions (by ID, round, script), ban scripts, and pardon convictions; conviction model and storage implemented across backends; configurable ban duration and threshold; earlier ban checks that can block or auto-ban during registration/submission/finalization flows.

- **Bug Fixes**
  - Forfeit validation now enforces Taproot script-spend signatures; missing UTXO entries are skipped instead of aborting retrieval.

- **Tests**
  - Conviction repository unit tests and new end-to-end TestBan covering nonce/signature/forfeit/boarding scenarios.

### CODE REVIEW

File: pkg/ark-lib/tree/musig2.go [hunk 1]
```diff
@@ -383,14 +384,72 @@ func (t *treeCoordinatorSession) AddNonce(pubkey *btcec.PublicKey, nonce TreeNon
...
+		}
+
+		if !sig.Verify(nonce.PubNonce, combinedNonce.PubNonce, cosigners, pubkey, [32]byte(message), musig2.WithTaprootSignTweak(t.scriptRoot)) {
+			return true, fmt.Errorf("invalid signature for txid %s", txid)
+		}
+	}
+
 	t.sigs[hex.EncodeToString(schnorr.SerializePubKey(pubkey))] = sig
+	return false, nil
 }
```
[the remark this answers is not in the document]
Comment (louisinger) [reply pkg/ark-lib/tree/musig2.go:443]: this is out of context regarding the PR changes

[the remark this answers is not in the document]
Comment (louisinger) [reply pkg/ark-lib/tree/musig2.go:443]: I've added len checks before casting to [32]byte(message)

[the remark this answers is not in the document]
Comment (louisinger) [reply pkg/ark-lib/tree/musig2.go:443]: but it works, are u sure ?
cc @altafan ?

File: api-spec/protobuf/ark/v1/admin.proto [hunk 2]
```diff
@@ -152,4 +184,82 @@ message Output {
...
+  string round_id = 2;
+  string reason = 3;
+}
+
+message Conviction {
+  string id = 1;
+  ConvictionType type = 2;
+  int64 created_at = 3;
+  int64 expires_at = 4; // 0 if never expires
+  Crime crime = 5;
```
Comment (altafan) [inline api-spec/protobuf/ark/v1/admin.proto]:
```suggestion
  repeated Crime crimes = 5;
```

File: internal/config/config.go [hunk 3]
```diff
@@ -73,6 +73,8 @@ type Config struct {
 	EventDbUrl          string
 	EventDbDir          string
 	RoundInterval       int64
+	BanDuration         int64
+	BanThreshold        int // number of convictions to trigger a ban
```
Comment (altafan) [inline internal/config/config.go]:
```suggestion
	BanThreshold        int // number of crimes to trigger a ban (conviction)
```

File: internal/core/application/service.go [hunk 4]
```diff
@@ -1764,6 +1787,9 @@ func (s *service) startFinalization(
 			)
 			s.cache.CurrentRound().Fail(err)
 			log.Warn(err)
+
+			// ban all the scripts that didn't submitted their nonces
+			s.banNoncesCollectionTimeout(roundId, signingSession, registeredIntents)
```
Comment (altafan) [inline internal/core/application/service.go]: could be done in a go routine?

File: internal/core/application/service.go [hunk 5]
```diff
@@ -1924,17 +1989,17 @@ func (s *service) finalizeRound(roundTiming roundTiming) {
...
 		log.WithError(err).Warn("failed to parse commitment tx")
 		return
 	}
 
 	commitmentTxid := commitmentTx.UnsignedTx.TxID()
 	includesBoardingInputs := s.cache.BoardingInputs().Get() > 0
-	txToSign := s.cache.CurrentRound().Get().CommitmentTx
 	forfeitTxs := make([]domain.ForfeitTx, 0)
 
+	txToSign := s.cache.CurrentRound().Get().CommitmentTx
```
Comment (altafan) [inline internal/core/application/service.go:1999]: REVERT!

File: api-spec/protobuf/ark/v1/admin.proto (hunk 2 above)
Comment (louisinger) [reply api-spec/protobuf/ark/v1/admin.proto]: a Crime is a subset of a conviction. 1 conviction is always associated with ONLY 1 crime

File: internal/config/config.go [hunk 6]
```diff
@@ -379,6 +389,12 @@ func (c *Config) Validate() error {
 	if c.RoundInterval < 2 {
 		return fmt.Errorf("invalid round interval, must be at least 2 seconds")
 	}
+	if c.BanDuration < 1 {
+		return fmt.Errorf("invalid ban duration, must be at least 1 second")
+	}
+	if c.BanThreshold < 1 {
```
Comment (altafan) [inline internal/config/config.go:395]: let the autoban be disabled with values below 1

File: internal/core/domain/conviction_repo.go [hunk 7]
```diff
@@ -0,0 +1,14 @@
+package domain
+
+import "time"
+
+type ConvictionRepository interface {
+	Get(id string) (Conviction, error)
```
Comment (altafan) [inline internal/core/domain/conviction_repo.go]: add ctx to all apis

File: internal/core/ports/live_store.go [hunk 8]
```diff
@@ -38,6 +38,7 @@ type ForfeitTxsStore interface {
 	Reset()
 	Pop() ([]string, error)
 	AllSigned() bool
+	UnsignedVtxoKeys() []domain.Outpoint
```
Comment (altafan) [inline internal/core/ports/live_store.go]:
```suggestion
	UnsignedInputs() []domain.Outpoint
```
