### PR TITLE
Forfeit transactions: signing process

### LINKED ISSUE #77: Faucet fails randomly with "2 forfeit txs left to sign" message
`noah faucet` fails most of the time with the error message "2 forfeits txs left to sign". It also happens to see a "not in a valid stage to register payments"

### PR DESCRIPTION
**Pull request by louisinger**
_This PR adds forfeit transactions signing process into Noah CLI, it also introduces some changes on ark service & tx builder_

### Ark service

* Delete `SignVtxos`: only the client signs the forfeit transactions
* Add `UpdateForfeitTxs` triggered while the client fires `FinalizePayment`
* The ASP verifies forfeit transactions' signatures while receiving them

### TxBuilder

* add fee output to forfeit transaction
* add connector amount to "forfeit output"
* add witnessUtxo to forfeit transaction inputs
* fix `connectorsToInputArgs` func = do not add 2 connectors for the last pset in case we only have 1 (mostly faucet case)

### Noah

* move the Stream handling function into the `common.go` file: use the function for send and redeem.
* handle forfeit transactions signing while finalizing a payment (collaborative exit & send)

it closes #77 

@altafan please review

### CODE REVIEW

File: asp/internal/core/application/service.go [hunk 1]
```diff
@@ -30,7 +30,7 @@ type Service interface {
 	Stop()
 	SpendVtxos(ctx context.Context, inputs []domain.VtxoKey) (string, error)
 	ClaimVtxos(ctx context.Context, creds string, receivers []domain.Receiver) error
-	SignVtxos(ctx context.Context, forfeitTxs []string) error
+	UpdateForfeitTxs(ctx context.Context, forfeitTxs []string) error
```
Comment (altafan) [inline asp/internal/core/application/service.go]: revert renaming

File: asp/internal/core/application/utils.go [hunk 2]
```diff
@@ -138,39 +144,85 @@ type signedTx struct {
...
+				break
+			}
+		}
+
+		m.forfeitTxs[utx.TxHash().String()] = &signedTx{tx, signed}
 	}
 }
 
-func (m *forfeitTxsMap) sign(txs []string) error {
+func (m *forfeitTxsMap) update(txs []string) error {
```
Comment (altafan) [inline asp/internal/core/application/utils.go]: revert renaming

Comment (altafan) [reply asp/internal/core/application/utils.go]: also, the genesis block hash can be passed here instead of passing the whole network to the factory

File: asp/internal/core/application/utils.go [hunk 3]
```diff
@@ -160,17 +179,49 @@ func (m *forfeitTxsMap) sign(txs []string) error {
...
-		ptx, err := psetv2.NewPsetFromBase64(tx)
-		if err != nil {
-			return fmt.Errorf("invalid forfeit tx format")
-		}
+		ptx, _ := psetv2.NewPsetFromBase64(tx)
 		utx, _ := ptx.UnsignedTx()
-		txid := utx.TxHash().String()
-		if _, ok := m.forfeitTxs[txid]; !ok {
-			return fmt.Errorf("forfeit tx %s not found", txid)
+
```
Comment (altafan) [inline asp/internal/core/application/utils.go:185]: please restore `txid := utx.TxHash().String()` as it can be reused the line above but also in L215

**Review by altafan — APPROVED** [review]
